//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnCuoiKy_Medias.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyMediasEntities : DbContext
    {
        public QuanLyMediasEntities()
            : base("name=QuanLyMediasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<GenresMovies> GenresMovies { get; set; }
        public virtual DbSet<HistoryList> HistoryList { get; set; }
        public virtual DbSet<LikedList> LikedList { get; set; }
        public virtual DbSet<Movies> Movies { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistory { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<Playlist> Playlist { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<SubGenres> SubGenres { get; set; }
        public virtual DbSet<SubGenresMovies> SubGenresMovies { get; set; }
    }
}
